FROM {base_image}

ARG netcoreapp_version
ARG optional_restore_feeds

WORKDIR test
RUN dotnet new console --framework netcoreapp$netcoreapp_version
RUN dotnet restore $optional_restore_feeds
RUN dotnet build
