FROM $base_image

ARG netcoreapp_version
ARG optional_restore_args

WORKDIR test
RUN dotnet new console --framework netcoreapp$netcoreapp_version
RUN dotnet restore $optional_restore_args
RUN dotnet build
